### ISSUE TITLE
User suggestions

### ISSUE THREAD

**Issue by mccreery** [mccreery/better-hud#1]
- [x] CPS counter (clicks per second)
- [x] Move around vanilla HUD elements
- [x] Textual compass "N (-X)" rather than graphical
- [x] Allow reordering of elements to be drawn first
- [x] Auto-hide survival only values in creative
- [x] Possibility to set position relative to other elements

**Comment by Leosky** [comment]
Possibility to set position relative to other elements

**Comment by lezargv** [comment]
tht not work with apple skin all are movable tough there element
