### ISSUE TITLE
1.16.5 supported?

### ISSUE THREAD

**Issue by Gohirro** [mccreery/better-hud#126]
I am running Forge 1.16.5 version 36.1.0. I get the message at the title screen that states this mod is for an older version of minecraft and could not be loaded. I tried using the latest version of your mod (betterhud-1.12.2-1.4.4.jar). Is 1.16.5 not supported yet?

**Comment by mccreery** [comment]
1.12.2 is the latest version right now. I have been making efforts to update the mod, but this is only my hobby so it is a lot of work in that sense. I cannot guarantee a release date for the update.
