### ISSUE TITLE
Potion Effects default not turning back on?

### ISSUE THREAD

**Issue by UltraCyberGod** [mccreery/better-hud#22]
I used the potion display option in the HUD toggled the "Display default:off/on" after that the default has gone but whatever I do I cannot get it back? I've tried deleting config etc.

**Comment by mccreery** [comment]
Closing as the potion display has been rewritten to mimic the vanilla display (e486073dcb46ebad526a83fc920c72ddee0d54fc). When the mod is disabled, the vanilla potion display is shown as usual.
