### ISSUE TITLE
[ISSUE] Screen stuck with Shaders

### ISSUE THREAD

**Issue by SeanChengN** [mccreery/better-hud#28]
Hi, There is a issure when I use some shaders, Such as KUDA, Sildurs Vibrant Shaders.
**Image:**
![betterhud issure](https://user-images.githubusercontent.com/20624068/45789722-ab113680-bcb3-11e8-903c-d9f2419a4ea0.gif)

If I use "Mob Info" ,"Horse Info", "Breed Indicator", The screen will turn white or stuck when you point to animals.
But, SEUS is ok.
Can you fix it?

**Comment by mccreery** [comment]
Is the issue reproducible using the [latest beta version](https://minecraft.curseforge.com/projects/better-hud/files/2621232)?

**Comment by SeanChengN** [comment]
> Is the issue reproducible using the [latest beta version](https://minecraft.curseforge.com/projects/better-hud/files/2621232)?

Thx, It works.
