### ISSUE TITLE
[Suggestion] Custom UI Layouts

### ISSUE THREAD

**Issue by NovaViper** [mccreery/better-hud#36]
Hi, can there be custom layouts to resemble something like in RPG games? Similar to how the mod, [RPG Hud](https://minecraft.curseforge.com/projects/rpg-hud?gameCategorySlug=mc-mods&projectID=235670) has this option.

**Comment by mccreery** [comment]
You can lay out the elements however you want using the menu. There are options for anchoring to a side or corner, alignment, offset and (in the beta) a parent to anchor to instead of the whole screen. If this isn't your thing, that mod should (AFAIK) work fine if you install both, as Better HUD triggers all the same events that vanilla does when drawing the HUD.

**Comment by NovaViper** [comment]
@mccreery I mean a totally different layout, that overrides the vanilla UI

**Comment by mccreery** [comment]
This mod does override the vanilla UI. It doesn't provide alternative styles for each of the vanilla elements, but you can move them wherever you want. The mod you sent has these features, why not install both?

**Comment by NovaViper** [comment]
@mccreery That's what I have been using, but I have another issue relating with RPG hud entirely (which the author has been inactive for a long time now, so I'm doubting it will ever get fixed). And that issue is that it completely hides Tough as Nail's UI features (namely the thirst bar). I did try another mod (Ignite HUD) that actually has the display for Tough as Nails,  but it doesn't offer not nearly as many features as RPG hud does.

**Comment by mccreery** [comment]
This mod recently had the same bug. It could be possible that the next beta will fix your problems with RPG-Hud.

**Comment by mccreery** [comment]
Alternative styles could be in the scope of a future update, but I am focussing on stability and improvements to the main features for now. Closing this issue for now.
