### ISSUE TITLE
Active HUDs Disappear when riding a mount (such as a horse)  

### ISSUE THREAD

**Issue by SextupleTap** [mccreery/better-hud#37]
I am wondering if in the next release you can work towards the active HUDs staying visible when riding a mount, because in the current state of the mod, all active HUDs provided by your mod will disappear when you ride a mount, and they then reappear when you dismount the mount.

It could be nice to see HUDs (such as the compass hud + coordinate hud for example) while riding a mount like a horse.

Although, I will note that when using a feature such as the "Mob Info" HUD, it works just fine where when looking at a mob it will display the information above it (like health) properly when on or off of a mount.

**Comment by mccreery** [comment]
I believe this was a bug and has been fixed in the WIP beta version. I'm not sure, so I'll check and make sure it is by the next release. Thank you.

**Comment by mccreery** [comment]
Testing indicates that this issue has been fixed. Closing until the issue arises again.
