### ISSUE TITLE
Exception when  a mob hits you (java.util.Random.nextInt with negative value)

### ISSUE THREAD

**Issue by leterio** [mccreery/better-hud#38]
Tip, on uk.nukeduck.hud.util.MathUtil, before call to Random.next*, check if the number is negative, if is negative, multiply by -1.

STACKTRACE:
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Client thread
> Stacktrace:
> 	at java.util.Random.nextInt(Unknown Source)
> 	at tk.nukeduck.hud.util.MathUtil.randomRange(MathUtil.java:65)
> 	at tk.nukeduck.hud.util.MathUtil.randomPoint(MathUtil.java:78)
> 	at tk.nukeduck.hud.element.particles.ParticleBase.createRandom(ParticleBase.java:33)
> 	at tk.nukeduck.hud.element.particles.BloodSplatters.onEntityDamage(BloodSplatters.java:37)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_344_BloodSplatters_onEntityDamage_LivingDamageEvent.invoke(.dynamic)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
> 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
> 	at net.minecraftforge.common.ForgeHooks.onLivingDamage(ForgeHooks.java:596)
> 	at net.minecraft.entity.player.EntityPlayer.func_70665_d(EntityPlayer.java:1128)
> 	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:919)
> 	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1038)
> 	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:645)
> 	at micdoodle8.mods.galacticraft.core.entities.player.GCEntityPlayerMP.func_70097_a(GCEntityPlayerMP.java:68)
> 	at net.minecraft.entity.monster.EntityMob.func_70652_k(EntityMob.java:99)
> 	at net.minecraft.entity.monster.EntityZombie.func_70652_k(EntityZombie.java:294)
> 	at net.minecraft.entity.ai.EntityAIAttackMelee.func_190102_a(EntityAIAttackMelee.java:178)
> 	at net.minecraft.entity.ai.EntityAIAttackMelee.func_75246_d(EntityAIAttackMelee.java:167)
> 	at net.minecraft.entity.ai.EntityAIZombieAttack.func_75246_d(SourceFile:28)
> 	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
> 	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:888)
> 	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2352)
> 	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:678)
> 	at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:45)
> 	at net.minecraft.entity.monster.EntityZombie.func_70636_d(EntityZombie.java:223)
> 	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2172)
> 	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
> 	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
> 	at net.minecraft.world.World.func_72866_a(World.java:1993)
> 	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
> 	at net.minecraft.world.World.func_72870_g(World.java:1955)
> 
> -- Entity being ticked --
> Details:
> 	Entity Type: minecraft:zombie (net.minecraft.entity.monster.EntityZombie)
> 	Entity ID: 321986
> 	Entity Name: Zumbi
> 	Entity's Exact location: -222.58, 222.00, 298.50
> 	Entity's Block location: World: (-223,222,298), Chunk: (at 1,13,10 in -14,18; contains blocks -224,0,288 to -209,255,303), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
> 	Entity's Momentum: 0.01, -0.08, -0.06
> 	Entity's Passengers: []
> 	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
> Stacktrace:
> 	at net.minecraft.world.World.func_72939_s(World.java:1759)
> 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
> 
> -- Affected level --
> Details:
> 	Level name: Mundo pra jogar com a Lindanessa
> 	All players: 2 total; [GCEntityPlayerMP['Leterio'/307, l='Mundo pra jogar com a Lindanessa', x=-222.87, y=222.00, z=297.23], GCEntityPlayerMP['Vanessa'/11165, l='Mundo pra jogar com a Lindanessa', x=-251.58, y=227.00, z=245.95]]
> 	Chunk stats: ServerChunkCache: 767 Drop: 0
> 	Level seed: 6676492010719413537
> 	Level generator: ID 04 - customized, ver 0. Features enabled: true
> 	Level generator options: {"coordinateScale":684.0,"heightScale":684.0,"lowerLimitScale":64.0,"upperLimitScale":2.0,"depthNoiseScaleX":200.0,"depthNoiseScaleZ":200.0,"depthNoiseScaleExponent":0.5,"mainNoiseScaleX":80.0,"mainNoiseScaleY":160.0,"mainNoiseScaleZ":80.0,"baseSize":8.5,"stretchY":12.0,"biomeDepthWeight":1.0,"biomeDepthOffset":0.0,"biomeScaleWeight":1.0,"biomeScaleOffset":1.0,"seaLevel":63,"useCaves":true,"useDungeons":true,"dungeonChance":8,"useStrongholds":true,"useVillages":true,"useMineShafts":true,"useTemples":true,"useMonuments":true,"useMansions":true,"useRavines":true,"useWaterLakes":true,"waterLakeChance":4,"useLavaLakes":true,"lavaLakeChance":80,"useLavaOceans":false,"fixedBiome":-1,"biomeSize":4,"riverSize":4,"dirtSize":33,"dirtCount":10,"dirtMinHeight":0,"dirtMaxHeight":255,"gravelSize":33,"gravelCount":8,"gravelMinHeight":0,"gravelMaxHeight":255,"graniteSize":33,"graniteCount":10,"graniteMinHeight":0,"graniteMaxHeight":192,"dioriteSize":33,"dioriteCount":10,"dioriteMinHeight":0,"dioriteMaxHeight":192,"andesiteSize":33,"andesiteCount":10,"andesiteMinHeight":0,"andesiteMaxHeight":192,"coalSize":17,"coalCount":20,"coalMinHeight":0,"coalMaxHeight":192,"ironSize":9,"ironCount":20,"ironMinHeight":0,"ironMaxHeight":128,"goldSize":9,"goldCount":2,"goldMinHeight":0,"goldMaxHeight":64,"redstoneSize":8,"redstoneCount":8,"redstoneMinHeight":0,"redstoneMaxHeight":48,"diamondSize":8,"diamondCount":1,"diamondMinHeight":0,"diamondMaxHeight":32,"lapisSize":7,"lapisCount":1,"lapisCenterHeight":24,"lapisSpread":24}
> 	Level spawn location: World: (-212,64,240), Chunk: (at 12,4,0 in -14,15; contains blocks -224,0,240 to -209,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
> 	Level time: 1187222 game time, 1227659 day time
> 	Level dimension: 0
> 	Level storage version: 0x04ABD - Anvil
> 	Level weather: Rain time: 103162 (now: false), thunder time: 114347 (now: false)
> 	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
> Stacktrace:
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
> 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
> 	at java.lang.Thread.run(Unknown Source)
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.12.2
> 	Operating System: Windows 10 (amd64) version 10.0
> 	Java Version: 1.8.0_191, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 417063960 bytes (397 MB) / 2360496128 bytes (2251 MB) up to 4281597952 bytes (4083 MB)
> 	JVM Flags: 3 total; -Xmn128M -Xmx4096M -XX:+UseConcMarkSweepGC
> 	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
> 	FML: MCP 9.42 Powered by Forge 14.23.5.2768 Optifine OptiFine_1.12.2_HD_U_E1 52 mods loaded, 52 mods active
> 	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
> 
> 	| State     | ID                        | Version                  | Source                                        | Signature                                |
> 	|:--------- |:------------------------- |:------------------------ |:--------------------------------------------- |:---------------------------------------- |
> 	| UCHIJAAAA | minecraft                 | 1.12.2                   | minecraft.jar                                 | None                                     |
> 	| UCHIJAAAA | mcp                       | 9.42                     | minecraft.jar                                 | None                                     |
> 	| UCHIJAAAA | FML                       | 8.0.99.99                | forge-1.12.2-14.23.5.2768.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
> 	| UCHIJAAAA | forge                     | 14.23.5.2768             | forge-1.12.2-14.23.5.2768.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
> 	| UCHIJAAAA | micdoodlecore             |                          | minecraft.jar                                 | None                                     |
> 	| UCHIJAAAA | buildcraftlib             | 7.99.19                  | buildcraft-7.99.19.jar                        | None                                     |
> 	| UCHIJAAAA | buildcraftcore            | 7.99.19                  | buildcraft-7.99.19.jar                        | None                                     |
> 	| UCHIJAAAA | buildcraftfactory         | 7.99.19                  | buildcraft-7.99.19.jar                        | None                                     |
> 	| UCHIJAAAA | buildcrafttransport       | 7.99.19                  | buildcraft-7.99.19.jar                        | None                                     |
> 	| UCHIJAAAA | buildcraftsilicon         | 7.99.19                  | buildcraft-7.99.19.jar                        | None                                     |
> 	| UCHIJAAAA | additionalpipes           | 6.0.0.8                  | additionalpipes-6.0.0.8.jar                   | None                                     |
> 	| UCHIJAAAA | hud                       | 1.4-beta                 | Better-HUD-Mod-1.12.2.jar                     | None                                     |
> 	| UCHIJAAAA | bookshelf                 | 2.3.568                  | Bookshelf-1.12.2-2.3.568.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
> 	| UCHIJAAAA | buildcraftbuilders        | 7.99.19                  | buildcraft-7.99.19.jar                        | None                                     |
> 	| UCHIJAAAA | buildcraftenergy          | 7.99.19                  | buildcraft-7.99.19.jar                        | None                                     |
> 	| UCHIJAAAA | buildcraftrobotics        | 7.99.19                  | buildcraft-7.99.19.jar                        | None                                     |
> 	| UCHIJAAAA | ic2                       | 2.8.102-ex112            | industrialcraft-2-2.8.102-ex112.jar           | None                                     |
> 	| UCHIJAAAA | jei                       | 4.13.1.222               | jei_1.12.2-4.13.1.222.jar                     | None                                     |
> 	| UCHIJAAAA | forestry                  | 5.8.2.372                | forestry_1.12.2-5.8.2.372.jar                 | None                                     |
> 	| UCHIJAAAA | buildcraftcompat          | 7.99.15                  | buildcraft-compat-7.99.15.jar                 | None                                     |
> 	| UCHIJAAAA | codechickenlib            | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
> 	| UCHIJAAAA | chickenchunks             | 2.4.1.73                 | ChickenChunks-Mod-1.12.2.jar                  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
> 	| UCHIJAAAA | cxlibrary                 | 1.6.1                    | cxlibrary-1.12.1-1.6.1.jar                    | None                                     |
> 	| UCHIJAAAA | eplus                     | 5.0.163                  | Enchanting-Plus-Mod-1.12.2.jar                | d476d1b22b218a10d845928d1665d45fce301b27 |
> 	| UCHIJAAAA | gottschcore               | 1.5.1                    | GottschCore-mc1.12.2-f14.23.5.2768-v1.5.1.jar | None                                     |
> 	| UCHIJAAAA | fastladder                | 1.1.1                    | FastLadder-mc1.12.2-f14.23.5.2768-v1.1.1.jar  | None                                     |
> 	| UCHIJAAAA | forgemultipartcbe         | 2.6.0.79                 | ForgeMultipart-1.12.2-2.6.0.79-universal.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
> 	| UCHIJAAAA | microblockcbe             | 2.6.0.79                 | ForgeMultipart-1.12.2-2.6.0.79-universal.jar  | None                                     |
> 	| UCHIJAAAA | minecraftmultipartcbe     | 2.6.0.79                 | ForgeMultipart-1.12.2-2.6.0.79-universal.jar  | None                                     |
> 	| UCHIJAAAA | galacticraftcore          | 4.0.1.181                | GalacticraftCore-1.12.2-4.0.1.181.jar         | None                                     |
> 	| UCHIJAAAA | ichunutil                 | 7.1.4                    | iChun-Util-Mod-1.12.2.jar                     | None                                     |
> 	| UCHIJAAAA | inventorytweaks           | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                      | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
> 	| UCHIJAAAA | metalchests               | v3.9.0.g9b0c79e          | MetalChests-v3.9.0.g9b0c79e.jar               | None                                     |
> 	| UCHIJAAAA | morefurnaces              | 1.10.1                   | More-Furnaces-Mod-1.12.1.jar                  | None                                     |
> 	| UCHIJAAAA | mrtjpcore                 | 2.1.3.35                 | MrTJPCore-1.12.2-2.1.3.35-universal.jar       | None                                     |
> 	| UCHIJAAAA | nei                       | 2.4.2                    | NotEnoughItems-1.12.2-2.4.2.240-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
> 	| UCHIJAAAA | portalgun                 | 7.0.2                    | Portal-Gun-Mod-1.12.2.jar                     | None                                     |
> 	| UCHIJAAAA | projectred-core           | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-Base.jar           | None                                     |
> 	| UCHIJAAAA | projectred-compat         | 1.0                      | ProjectRed-1.12.2-4.9.1.92-compat.jar         | None                                     |
> 	| UCHIJAAAA | projectred-integration    | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-integration.jar    | None                                     |
> 	| UCHIJAAAA | projectred-transmission   | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-integration.jar    | None                                     |
> 	| UCHIJAAAA | projectred-fabrication    | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-fabrication.jar    | None                                     |
> 	| UCHIJAAAA | projectred-illumination   | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-lighting.jar       | None                                     |
> 	| UCHIJAAAA | projectred-expansion      | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-mechanical.jar     | None                                     |
> 	| UCHIJAAAA | projectred-relocation     | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-mechanical.jar     | None                                     |
> 	| UCHIJAAAA | projectred-transportation | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-mechanical.jar     | None                                     |
> 	| UCHIJAAAA | projectred-exploration    | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-world.jar          | None                                     |
> 	| UCHIJAAAA | spawnercraft              | 4.0.0                    | SpawnerCraft 1.12.2-4.0.0.jar                 | None                                     |
> 	| UCHIJAAAA | bspkrscore                | at_0.9                   | TreeCapitator-Mod-1.12.jar                    | None                                     |
> 	| UCHIJAAAA | treecapitator             | at_0.9                   | TreeCapitator-Mod-1.12.jar                    | None                                     |
> 	| UCHIJAAAA | twilightforest            | 3.8.689                  | twilightforest-1.12.2-3.8.689-universal.jar   | None                                     |
> 	| UCHIJAAAA | xaerominimap              | 1.15.8                   | Xaeros-Minimap-Mod-1.12.jar                   | None                                     |
> 
> 	Loaded coremods (and transformers): 
> Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
>   invtweaks.forge.asm.ContainerTransformer
> MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.181.jar)
>   micdoodle8.mods.miccore.MicdoodleTransformer
> CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
>   cubex2.cxlibrary.CoreModTransformer
> 	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
> 	forestry : Modules have been disabled in the config: Book, Mail, Backpack
> 	Profiler Position: N/A (disabled)
> 	Player Count: 2 / 8; [GCEntityPlayerMP['Leterio'/307, l='Mundo pra jogar com a Lindanessa', x=-222.87, y=222.00, z=297.23], GCEntityPlayerMP['Vanessa'/11165, l='Mundo pra jogar com a Lindanessa', x=-251.58, y=227.00, z=245.95]]
> 	Type: Integrated Server (map_client.txt)
> 	Is Modded: Definitely; Client brand changed to 'fml,forge'
> 	OptiFine Version: OptiFine_1.12.2_HD_U_E1
> 	OptiFine Build: 20180628-111228
> 	Render Distance Chunks: 12
> 	Mipmaps: 4
> 	Anisotropic Filtering: 1
> 	Antialiasing: 0
> 	Multitexture: false
> 	Shaders: null
> 	OpenGlVersion: 4.5.13492 Compatibility Profile Context 22.19.677.257
> 	OpenGlRenderer: Radeon(TM) RX 460 Graphics
> 	OpenGlVendor: ATI Technologies Inc.
> 	CpuCount: 4
> [00:42:49] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
> [00:42:50] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'Mundo pra jogar com a Lindanessa'/overworld
> [00:42:50] [main/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# D:\Jogos\Minecraft\Client\.minecraft\crash-reports\crash-2018-12-16_00.42.48-server.txt
> [00:42:50] [main/INFO] [FML]: Waiting for the server to terminate/save.
> [00:42:51] [Server thread/INFO] [FML]: Unloading dimension 0
> [00:42:52] [Server thread/INFO] [FML]: Applying holder lookups
> [00:42:52] [Server thread/INFO] [FML]: Holder lookups applied
> [00:42:52] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -28
> [00:42:52] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.
> [00:42:52] [main/INFO] [FML]: Server terminated.
> [00:42:52] [Client Shutdown Thread/INFO] [minecraft/MinecraftServer]: Stopping server
> Exception in thread "Client Shutdown Thread" AL lib: (EE) alc_cleanup: 1 device not closed

**Comment by mccreery** [comment]
This issue has been fixed already.
