### ISSUE TITLE
[Suggestion] In Game Configuration

### ISSUE THREAD

**Issue by NovaViper** [mccreery/better-hud#4]
It would **_really_** help if this mod had a in-game configuration menu like many other mods feature now. The system is relatively easy to add in via Forge's hooks, I've made some in my mods before (you can look on my Github profile for them).  

Adding it would make changing the settings much easier than having to guess on the numbers with each Minecraft restart (and I have **many** mods, so it takes forever to all load up). Also, the changes should be able to load up instantly without having to restart the game (if that configuration can handle that though) Thanks! 👍

**Comment by mccreery** [comment]
The mod already has an extensive in-game configuration menu. The default button to open this menu is U, but this can be configured in the vanilla key config menu.

**Comment by NovaViper** [comment]
Ooh ok! Thanks for telling me :D

I thought they were in the Forge in game configuration menu

**Comment by mccreery** [comment]
I have considered moving my menu there, although I'm not sure it would support the current system or the positioning/snapping system for moving elements around. I will look into it at some point.
