### ISSUE TITLE
Block Viewer shows no text or item (blank) with certain mods

### ISSUE THREAD

**Issue by mccreery** [mccreery/better-hud#44]
https://minecraft.curseforge.com/projects/better-hud?comment=120
https://minecraft.curseforge.com/projects/better-hud?comment=111

**Comment by mccreery** [comment]
This issue also occurs using Sonic Ether's Unbelievable Shaders (most likely other shaders as well). Fast Render is incompatible with shaders, so they may do the same thing which causes this bug.

**Comment by DPattee** [comment]
I have 'Fast Render' off and don't have any text in the block info display.

I am using Sildburs Vibrant Shaders though. 

Note that the block info box worked with this same shader on the HUD 1.3.9 release.
