### ISSUE TITLE
Galacticraft Crash

### ISSUE THREAD

**Issue by mccreery** [mccreery/better-hud#46]
https://minecraft.curseforge.com/projects/better-hud?comment=118

**Comment by cjser** [comment]
Getting randoms crashes with galacticraft core (and other mods) when fighting monsters. 

Crash report: 
[crash-2019-01-19_02.54.48-client.txt](https://github.com/mccreery/better-hud/files/2780113/crash-2019-01-19_02.54.48-client.txt)
Config:
[Ser.cfg.txt](https://github.com/mccreery/better-hud/files/2780115/Ser.cfg.txt)
 Steps to reproduce/extra information: Happens ramdomly when I am fighting a monster, generally the one from mods, it crashes to title screen.

**Comment by mccreery** [comment]
Please update to [v1.4-beta.3](https://github.com/mccreery/better-hud/tree/v1.12.2-beta.3), you're a version behind. This has been fixed.

**Comment by cjser** [comment]
Not fixed. Updated to beta3 still crash when fighting mobs
