### ISSUE TITLE
Newly saved config doesn't appear in the list

### ISSUE THREAD

**Issue by DPattee** [mccreery/better-hud#49]
After typing a new name and clicking 'Save' nothing appears to happen. So I clicked save multiple times... 

It wasn't until I left the Load/Save screen and came back again later that I discovered there were now multiple copies of the config I'd saved.

Suggestion: Upon a successful 'Save' the name input box should be emptied and the list of saved configuration names should be immediately updated. 

Optional: The config name that was just saved should be highlighted / different color in that list to help make it more obvious that the file was saved.

**Comment by mccreery** [comment]
Right now the text box is filled/stays filled based on which file is selected in the list. Saving a file should add it to the list and highlight it (fix incoming, I missed a func call). I'll be making some more changes to the save/load menu in future updates, but for 1.4 the menu should be functional after this fix. Thanks for reporting.
