### ISSUE TITLE
Client Crashing on Multiplayer Server With AutoPackager Mod

### ISSUE THREAD

**Issue by FriendlyGamer** [mccreery/better-hud#53]
All I literally did was /home on my server and it crashed my client even on client's restart and reconnecting.  

I am suspecting this mod is not playing "nice" with AutoPackager according to my hosting provider. Due to the crash report structure and the fact this mod still a BETA product.  

Related contents are in this ZIP file. Including the Crash Report and the configs of both mods. 
[betterhud.zip](https://github.com/mccreery/better-hud/files/2897436/betterhud.zip)

**Comment by mccreery** [comment]
I have just read the crash report, but this is most likely a problem with AutoPackager and not Better HUD. I had another mod with a very similar problem recently. If you haven't already, post the same crash over there, as it will likely be an easy fix (NPEs usually are).

**Comment by FriendlyGamer** [comment]
Ahh okay, I will post it there and see what they says. I will also point them here so they understand that you already looked at it.  

The core reason I put it here was... 
A. The server wasn't faulting (so it's indicated more towards the client than say a block issue)  
B. It clearly listed the original suspected mod to cause a concern to post it here.  

But nevertheless I will see if they indeed fix it in a snap.

**Comment by mccreery** [comment]
yeah, the issue is definitely related to this mod (part of the block viewer) but this crash should still never happen. It can be hard to test for all these things since there isn't all that much documentation for rules your tile entities must follow apart from working on their own.

**Comment by FriendlyGamer** [comment]
Ahh I gotcha, yea it's a PITR if there not much standards to adhere to begin with. :(
