### ISSUE TITLE
Crash with ChocoCraft 3

### ISSUE THREAD

**Issue by OwenLouise** [mccreery/better-hud#57]
Game crashed when a new choco egg was born or placed.(crash-report attached)
[crash-2019-04-10_19.38.42-client.txt](https://github.com/mccreery/better-hud/files/3063624/crash-2019-04-10_19.38.42-client.txt)

**Comment by mccreery** [comment]
Slayer5934/ChocoCraft3SLY#32

**Comment by OwenLouise** [comment]
The problem has been solved in the newest update of chococraft.Thx.:smile:
