### ISSUE TITLE
Scoreboard not displaying in Hypixel

### ISSUE THREAD

**Issue by Alstro20** [mccreery/better-hud#59]
Scoreboard functions perfectly in offline, but when connected to Hypixel the scoreboard doesn't show at all, whether or not it is enabled. Only solution is to completely disable BetterHud.

Tested on other servers and the issue isn't present. Maybe it's a plugin Hypixel is using?

**Comment by OfficialMajonese** [comment]
Is there a solution to this?

**Comment by mccreery** [comment]
Yeah, it's been fixed. The solution will be in the next build.
