### ISSUE TITLE
Crash with astral sorcery

### ISSUE THREAD

**Issue by cjser** [mccreery/better-hud#61]
Getting crash to main screen when I try to break the spectral relays of astral sorcery.
[crash-2019-05-04_02.36.42-client.txt](https://github.com/mccreery/better-hud/files/3144072/crash-2019-05-04_02.36.42-client.txt)

**Comment by mccreery** [comment]
Duplicate of #53 and several others. Read the first line of the stacktrace (`at hellfirepvp.astralsorcery...`). This is caused by that mod. I know why it happens, read #53 for details.
