### ISSUE TITLE
Interaction with Ferdzz/PlaceableItems causes game to crash

### ISSUE THREAD

**Issue by BestMordaEver** [mccreery/better-hud#67]
Mod Placeable Items allows you to place items on different surfaces (duh), where they become interactable blocks, and you can break the block to retrieve the item. 
BHUD causes game to crash if enchanted sword is picked up in such fashion. Specifically, several seconds after you break the sword block (which doesn't drop the sword) the game freezes and crashes. It consistently happens with mod enabled in the BHUD menu and inconsistently with mod being disabled.
Yes, it works perfectly without BHUD. I will post the same issue to Ferdzz.
[latest.log](https://github.com/mccreery/better-hud/files/3363504/latest.log)
[crash-2019-07-05_19.37.46-server.txt](https://github.com/mccreery/better-hud/files/3363506/crash-2019-07-05_19.37.46-server.txt)

**Comment by mccreery** [comment]
See the option to disable NBT storage in the block viewer. That functionality will be removed from the next version because of this and many similar crashes.
