### ISSUE TITLE
Scaling Bug

### ISSUE THREAD

**Issue by Arctic90x** [mccreery/better-hud#68]
I find a small bug if you move stuff around where you want it and like but are in full-screen mode and go into window mode it does not scale right, it looks minor but still kinda buggy to me to see how half my toolbar is gone

**Comment by mccreery** [comment]
That's not a bug. You can use the anchor/alignment controls in the settings menu to anchor an element to a side or corner of the screen so resizing the window won't cause an issue. If you're talking about something else, please open another issue or reply here if you have more questions about anchoring.
