### ISSUE TITLE
A few issues and suggestions with certain mods

### ISSUE THREAD

**Issue by NovaViper** [mccreery/better-hud#7]
Hey, I notice that with the arrow counter doesn't appear for custom bows and arrows such as in the SwitchBow mod. Also, with mods like WAILA and OneProbe, this mod should automatically disable the entity/block viewing features or better yet, add those features onto those mods. 
Also, there's alot of interfance elements where the mod, Quark conflicts (doesn't cause a crash but can be confusing to find out which mod is what) with this mod, which the two should be able to detect each other and disable each other concurrently (or ask the player to compare the two settings and decide which one to disable)

**Comment by mccreery** [comment]
See #1 where I have added your idea for detecting the presence of other mods for default values. I'm not sure what you mean by Quark conflicts, if you could give specific examples I will be able to take a look at them.

**Comment by NovaViper** [comment]
Oh nvm, what I was talking about the Quark conflicts was relating to the Horse Info in this mod and the Mount information in Quark (the Quark version shows your hunger while your riding on the horse, while BH shows the information specifically about a horse)

**Comment by NovaViper** [comment]
Oh! I just found what parts of Quark conflicts with BetterHud. The Usage Ticker in Quark ("A small interface addition shows up next to the hotbar when items are used, or armor takes damage. This shows how many items or blocks you have left, or how the status of your armor is.
") it's very much like the armor display and the arrow/item displays in BetterHUD

As this feature is hard to demonstrate in a static picture, click the picture icon in the bottom of this card to see a demo gif.)

**Comment by mccreery** [comment]
I'm not sure I understand. All the features of this mod can be disabled if you use a similar feature from another mod. The menu is opened by default with U.

**Comment by NovaViper** [comment]
I honestly forgot what the issue was now 😆 . Whatever it was, it doesn't seem to be something that bothers me anymore. Thanks for looking into the issue!
