### ISSUE TITLE
Crash when looking at cable Applied Energistics 2

### ISSUE THREAD

**Issue by HyperWrench** [mccreery/better-hud#71]
Crash occurs when I look at the glass cable from AE2.

Mods leading to an error:
* appliedenergistics2-rv6-stable-7,
* Hwyla-1.8.26-B41_1.12.2 / theoneprobe-1.12-1.4.28,
* betterhud-1.12.2-1.4

[лог.txt](https://github.com/mccreery/better-hud/files/3447693/default.txt)
[crash-2019-07-31_01.01.13-client.txt](https://github.com/mccreery/better-hud/files/3447694/crash-2019-07-31_01.01.13-client.txt)
[4.cfg](https://github.com/mccreery/better-hud/files/3449701/4.txt)

**Comment by zsn741656478** [comment]
The same.

**Comment by mccreery** [comment]
Fixed by 7a17723.
