### ISSUE TITLE
Server crashes on startup (with betterhud only)

### ISSUE THREAD

**Issue by rborsato** [mccreery/better-hud#73]
My 1.12.2 forge server crashes on startup with only betterhud-1.12.2-1.4.1 in mods folder.
Here is the crash report:
[crash-2019-09-05_20.21.26-server.txt](https://github.com/mccreery/better-hud/files/3581557/crash-2019-09-05_20.21.26-server.txt)

**Comment by Klebestreifen** [comment]
The problem is that classes of the package "net.minecraft.client" are repeatedly accessed even though they are not loaded when the server is started.

**Comment by mccreery** [comment]
This mod is in desperate need of a SidedProxy. I will start working on it soon.
