### ISSUE TITLE
BetterHUD crashing when interacting wirh raw silicone ore from Galacticraft 4

### ISSUE THREAD

**Issue by Wrobel1111** [mccreery/better-hud#82]
Hey,
BetterHUD is crashing when I look with BetterHUD (all features enabled) at a block of [raw silicone ore](https://wiki.micdoodle8.com/wiki/Silicon_Ore), (this article is quite old, it doesn't look exactly the same)
, with the result java.lang.ArrayIndexOutOfBoundsException: -1. I'm quite sure that's it.
Logs are quite messed with buildcraft errors, sorry about that, the main problem sits in the end.
Thanks
[2020-01-24-6.log](https://github.com/mccreery/better-hud/files/4127945/2020-01-24-6.log)

**Comment by mccreery** [comment]
This appears to be a Galacticraft issue, and only 1.12.2 is supported currently. 1.8.9 is unlikely to receive a backport.
