### ISSUE TITLE
Crash when looking up beyond ladder

### ISSUE THREAD

**Issue by DrunkenUnicyclist** [mccreery/better-hud#90]
My clients and I have a consistent crash on a specific part of our main ladder in the beneath. From this position, if you look up far enough past the ladder it crashes. If you don't look beyond the ladder, you're safe.

[crash-2020-05-14_23.51.11-client.txt](https://github.com/mccreery/better-hud/files/4635159/crash-2020-05-14_23.51.11-client.txt)

[betterhud.txt](https://github.com/mccreery/better-hud/files/4635175/betterhud.txt)

**Comment by mccreery** [comment]
I haven't been able to reproduce this using Rebirth of the Night, but I'm fairly certain it's fixed by [v1.4.2](https://www.curseforge.com/minecraft/mc-mods/better-hud/files/2963404) that I just released. Please confirm if so.
