### ISSUE TITLE
Can't zoom with scopes in Modern Warfare Mod

### ISSUE THREAD

**Issue by ILAIGG** [mccreery/better-hud#91]
Hi, i have an issue. Idk if I'm configuring bad or what, but when I aim with a scope in Modern Warfare mod, it doesn't zoom. How I can fix it?

Pd: sorry for my bad english :P

**Comment by mccreery** [comment]
Hi, could you explain how this issue is related to Better HUD?

**Comment by ILAIGG** [comment]
Forget it, I installed both mods and now it works correctly.  I honestly don't know what caused the failure, maybe they didn't download correctly
