### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by Yonk316** [mccreery/better-hud#95]
[crash-2020-05-23_15.33.29-client.txt](https://github.com/mccreery/better-hud/files/4672418/crash-2020-05-23_15.33.29-client.txt)
[latest.log](https://github.com/mccreery/better-hud/files/4672419/latest.log)

**Comment by mccreery** [comment]
Good catch, turns out if you don't have an existing config the mod passes `null` to everything, and in one case that `null` isn't handled properly. I will get this fixed quickly.

Note to self: I should consider using a config file to load the defaults instead of in code.

**Comment by mccreery** [comment]
This issue has cropped up a few times and I haven't released anything yet because there are big changed going on elsewhere. I will put out a bugfix release just after 1.4.2 so everyone has a version that at least doesn't crash on first install while I work on the rest.

**Comment by omerbadawy11** [comment]
I have this exact issue and i used the Vanilla cfg, except for any changes I make in-game doesn't apply to the config.. it all resets after every launch!

**Comment by mccreery** [comment]
Download the new version: https://www.curseforge.com/minecraft/mc-mods/better-hud/files/2980723
Let me know if you still have problems (with config files) or if that fixes them so I can close the issue for good.
