### ISSUE TITLE
[1.12.2] Config settings keep reseting

### ISSUE THREAD

**Issue by sor1n** [mccreery/better-hud#98]
Every time I start the game, regardless of what my settings were before, the ui disaplays everything. Everything is turned on and in whatever position they are by default. It is really frustrating to have to open the options menu. Every. Single. Time. Just to change the arrangements as they should be.

**Comment by mccreery** [comment]
Yes, it's broken in the latest release, but fixed in master. A lot of stuff going on behind the scenes for the next update.
